server:
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/animotion-db
      database: animotion-db
      transaction:
        enabled: true

jwt:
  secret:
    key: "439adb87583df62d6ef6ba54faf42945c9ca704f7069f975898d1f7210ad05f6"
  expiration: 24h

logging:
  level:
    org.springframework.messaging: TRACE
    org.springframework.web.socket: TRACE